[project]
name = "built-in-functions"
authors = []
description = ""
telemetry = true
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.example]
path = "contracts/example.clar"

[contracts.practice-contract-calls]
path = "contracts/practice-contract-calls.clar"

[contracts.practice-map-keyword]
path = "contracts/practice-map-keyword.clar"

[contracts.practice-tuple]
path = "contracts/practice-tuple.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
